WITH BOOK_SALES_SUM AS(
    SELECT
        BOOK_ID,
        SUM(SALES) AS SALES
    FROM 
        BOOK_SALES S
    WHERE
        SALES_DATE LIKE "2022-01%"
    GROUP BY
        BOOK_ID
)
SELECT 
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * IFNULL(S.SALES,0)) AS TOTAL_SALES
FROM
    BOOK B
JOIN
    AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
LEFT JOIN 
    BOOK_SALES_SUM S ON S.BOOK_ID = B.BOOK_ID
GROUP BY 
    AUTHOR_NAME, CATEGORY
ORDER BY
    B.AUTHOR_ID, B.CATEGORY DESC