-- 코드를 입력하세요
SELECT
    I.ANIMAL_ID,
    I.ANIMAL_TYPE,
    I.NAME
FROM
    ANIMAL_INS I
LEFT JOIN
    ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE
    LEFT(I.SEX_UPON_INTAKE, 6) = "Intact" AND
    (LEFT(O.SEX_UPON_OUTCOME, 8) = "Neutered" OR
    LEFT(O.SEX_UPON_OUTCOME, 6) = "Spayed")
ORDER BY 
    I.ANIMAL_ID