# 서울에 위치한 식당들
SELECT
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
FROM 
    REST_REVIEW R
JOIN
    REST_INFO I ON R.REST_ID = I.REST_ID
WHERE
    I.ADDRESS LIKE "서울%"
GROUP BY
    I.REST_ID
ORDER BY
    AVG(R.REVIEW_SCORE) DESC, FAVORITES DESC 
    