SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT(S.USER_ID)) AS PUCHASED_USERS,
    ROUND(
        COUNT(DISTINCT(S.USER_ID)) /
        (SELECT COUNT(*) AS USERS FROM USER_INFO WHERE JOINED LIKE "2021%")
    ,1) AS PUCHASED_RATIO
FROM 
    ONLINE_SALE S
LEFT JOIN
    USER_INFO I ON I.USER_ID = S.USER_ID
WHERE
    I.JOINED LIKE "2021%"
GROUP BY
    YEAR, MONTH
ORDER BY
    YEAR, MONTH