
# 테이블에서 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서
# 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 
# 대여 기록 ID와 대여 금액 리스트를 출력
# 금액을 기준으로 내림차순, 대여 기록 ID를 기준으로 내림차순

WITH PLAN AS(
    SELECT PLAN_ID, CAR_TYPE, DISCOUNT_RATE,
        IF(LENGTH(DURATION_TYPE) = 11, LEFT(DURATION_TYPE,1), LEFT(DURATION_TYPE,2)) 
        AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
)


SELECT 
    H.HISTORY_ID,
    MIN(
        IF(90<=DATEDIFF(END_DATE, START_DATE)+1, 
           ROUND((DATEDIFF(END_DATE, START_DATE)+1) * C.DAILY_FEE * (100- P.DISCOUNT_RATE) / 100), 
        IF(30<=DATEDIFF(END_DATE, START_DATE)+1, 
           ROUND((DATEDIFF(END_DATE, START_DATE)+1) * C.DAILY_FEE * (100- P.DISCOUNT_RATE) / 100), 
        IF(7<=DATEDIFF(END_DATE, START_DATE)+1, 
           ROUND((DATEDIFF(END_DATE, START_DATE)+1) * C.DAILY_FEE * (100- P.DISCOUNT_RATE) / 100),
           (DATEDIFF(END_DATE, START_DATE)+1) * C.DAILY_FEE
        )))
    ) AS FEE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN
    CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
LEFT JOIN
    PLAN P ON 
        P.CAR_TYPE = C.CAR_TYPE AND
        DATEDIFF(END_DATE, START_DATE)+1 >= P.DURATION_TYPE
WHERE
    C.CAR_TYPE = "트럭"
GROUP BY
    H.HISTORY_ID
ORDER BY 
    FEE DESC,  H.HISTORY_ID DESC
