WITH H AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
),
J AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT
    H.FLAVOR
FROM 
    H
JOIN
    J ON H.FLAVOR = J.FLAVOR
ORDER BY
    H.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3