-- 코드를 입력하세요
SELECT
    DISTINCT(H.CAR_ID) AS CAR_ID
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN
    CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
WHERE
    C.CAR_TYPE = "세단" and
    MONTH(H.START_DATE) = 10
ORDER BY
    H.CAR_ID DESC
    
    